### ISSUE TITLE
Change Colours of Pocsag Messages Background

### ISSUE THREAD

**Issue by Klammraute** [luarvique/ppa#24]
Hi, in which code line do the POCSAG messages receive their 'Random' color? I would prefer if all messages had the same color background. I searched for over an hour but didn't find it. It would be nice if I could get a little help. 👯‍♂️ 
![color](https://github.com/luarvique/ppa/assets/19589850/685e2412-230a-49d1-a4e0-c1e4722fb353)

**Comment by luarvique** [comment]
The colors are assigned based on the message CapCode, in order to easier track messages sent to the same addressee:

https://github.com/luarvique/openwebrx/blob/c3d651da748361daa3bb1c66e0e86eb04737ab59/owrx/toolbox.py#L240

Please, use regular emails for your further inquiries, unless you have actually issues with the OWRX+ PPA repository.
