### ISSUE TITLE
DAB channel bandwidth

### ISSUE THREAD

**Issue by hoehenunterschied** [luarvique/ppa#30]
The bandwidth of DAB channels is 1536MHz. In the OpenWebRX+ user interface the DAB channel bandwidth seems to be 2MHz, spanning into neighbour channels. Perhaps this is the reason I have poor reception quality. Often the presence of DAB+ signals is detected, but audio can't be decoded. Using different programms like AbracaDABra, SDRangel or welle.io, I can reliably receive all local DAB+ stations using the same antenna and same RTL-SDR receiver.

**Comment by luarvique** [comment]
You really have neighbourhood DAB channels? Oh well, since we do not have DAB in the US, cannot check. Try reporting this to @jketterl though, he has added DAB to OpenWebRX.

**Comment by jketterl** [comment]
Please use the [groups.io](https://groups.io/g/openwebrx) mailing list for support requests.

The bandwidth is 2.048MS/s, which is the sample rate the decoder runs at. This is based on implementation details and, in fact, the DAB specification, which gives a lot of measurements based on that exact sample rate. Since most of the processing in the decoder is based on FFT, it should not matter what happens outside of the active signal bandwidth.

**Comment by luarvique** [comment]
This has been addressed elsewhere.
